### ISSUE TITLE
xcode7 doesn't works

### ISSUE THREAD

**Issue by agan112** [jcavar/xcfui#14]
I had install xcfui from alcatraz.But when I restar my xcode , I can't find the "Find unused imports" item in the file menu.

**Comment by NSProgrammer** [comment]
ditto

**Comment by jcavar** [comment]
Ok, this should be fixed with latest pull request. Please reinstall and let me know if you still have problems.

**Comment by nickbit** [comment]
Installed the latest version on Xcode 7.2 (tried both Alcatraz and git repo install).
- Menu item appears
- Checked 'Find unused imports'
- Cleanup project
- Build

*No Run Script added to the project -> no warnings about unused imports*

I tried it several times.

Any suggestions?

**Comment by jcavar** [comment]
Hmmm, interesting. Do you have anything special in your project configuration?

**Comment by nickbit** [comment]
it is a workspace with CocoaPods

**Comment by jcavar** [comment]
Really not sure, do you have multiple targets maybe?

**Comment by Daij-Djan** [comment]
same here - don't see anything. I have a workspace with cocoa pods + multi target (2 apps, 4 other targets + X in pods)

**Comment by nickbit** [comment]
yes, mine is also multi target

**Comment by jcavar** [comment]
Yeah, I see it now as well. Not sure what is happening, it might take some time to investigate this. Thanks  for reporting!

**Comment by indragy** [comment]
I installed xcfui with alcatraz, but it does not appear, My Xcode is 7.3.1,why?

**Comment by jcavar** [comment]
I am still not sure why it doesn't work. I haven't had time yet to investigate this.

**Comment by HeidiHansen** [comment]
Still doesn't work.  Using Version 7.3 (7D175)

**Comment by andrewljohnson** [comment]
Also doesn't wok for me with multitarget project.

**Comment by pangyake** [comment]
TARGETS-info-DVTPlugInCompatibilityUUIDs,add string "AD68E85B-441B-4301-B564-A45E4919A6AD" "A16FF353-8441-459E-A50C-B071F53F51B7" "7265231C-39B4-402C-89E1-16167C4CC990" "ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C". xcode7 can load bundle。

**Comment by jcavar** [comment]
Thanks @pangyake! This is now pushed and I think this issue can now be closed.
